CREATE DATABASE DEMO1;
GO
USE DEMO1
GO
CREATE TABLE Taikhoan (
MaTaiKhoan int PRIMARY KEY,
TenTaiKhoan NVARCHAR(50) NOT NULL,
MatKhau NVARCHAR(50) NOT NULL,
Email NVARCHAR(50) NOT NULL,

);
GO
CREATE TABLE NguoiDung(
MaNguoiDung INT PRIMARY KEY,
TenNguoiDung VARCHAR(50) NOT NULL, 
SDT NVARCHAR(50) NOT NULL, 
DiaChi VARCHAR(50) NOT NULL,
NgaySinh DATE NOT NULL,
MaTaiKhoan INT NOT NULL,
FOREIGN KEY(MaTaiKhoan) REFERENCES TaiKhoan(MaTaiKhoan)
);
CREATE TABLE GioHang(
MaGioHang INT PRIMARY KEY,
TongThanhToan NVARCHAR(50) NOT NULL,
MaNguoiDung INT NOT NULL,
FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
);
GO
CREATE TABLE SanPham(
MaSanPham INT PRIMARY KEY,
TenSanPham VARCHAR(50) NOT NULL,
GiaSanPham DECIMAL(18,2) NOT NULL,
DiaChiShop NVARCHAR(100) NOT NULL,
SoLuotBan INT NOT NULL,
SoLuotDanhGia INT NOT NULL,
MaGioHang INT NOT NULL,
FOREIGN KEY(MaGioHang) REFERENCES GioHang(MaGioHang)
);
GO
CREATE TABLE Bill (
MaBill INT PRIMARY KEY,
TongThanhToan DECIMAL(18, 2) NOT NULL,
PhuongThucThanhToan NVARCHAR(50) NOT NULL,
CachVanChuyen NVARCHAR(50) NOT NULL,
MaGioHang INT NOT NULL,
MaNguoiDung INT NOT NULL,
FOREIGN KEY (MaGioHang) REFERENCES GioHang(MaGioHang),
FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
);
GO
CREATE TABLE Quyen (
MaQuyen INT PRIMARY KEY,
TenQuyen NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE PhanQuyen (
MaNguoiDung INT NOT NULL,
MaQuyen INT NOT NULL,
FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung),
FOREIGN KEY (MaQuyen) REFERENCES Quyen(MaQuyen)
);
GO
