CREATE DATABASE DEMO1;
GO
USE DEMO1
GO
CREATE TABLE Taikhoan (
MaTaiKhoan int PRIMARY KEY IDENTITY(1,1),
TenTaiKhoan NVARCHAR(50) NOT NULL,
MatKhau NVARCHAR(50) NOT NULL,
Email NVARCHAR(50) NOT NULL,

);
GO
CREATE TABLE NguoiDung(
MaNguoiDung INT PRIMARY KEY IDENTITY(1,1),
TenNguoiDung VARCHAR(50) NOT NULL, 
SDT NVARCHAR(50) NOT NULL, 
DiaChi VARCHAR(50) NOT NULL,
NgaySinh DATE NOT NULL,
MaTaiKhoan INT NOT NULL,
FOREIGN KEY(MaTaiKhoan) REFERENCES TaiKhoan(MaTaiKhoan)
);
CREATE TABLE GioHang(
MaGioHang INT PRIMARY KEY IDENTITY(1,1),
TongThanhToan NVARCHAR(50) NOT NULL,
MaNguoiDung INT NOT NULL,
FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
);
GO
CREATE TABLE SanPham(
MaSanPham INT PRIMARY KEY IDENTITY(1,1),
TenSanPham VARCHAR(50) NOT NULL,
GiaSanPham DECIMAL(18,2) NOT NULL,
DiaChiShop NVARCHAR(100) NOT NULL,
SoLuotBan INT NOT NULL,
SoLuotDanhGia INT NOT NULL,
MaGioHang INT NOT NULL,
FOREIGN KEY(MaGioHang) REFERENCES GioHang(MaGioHang)
);
GO
CREATE TABLE Bill (
MaBill INT PRIMARY KEY IDENTITY(1,1),
TongThanhToan DECIMAL(18, 2) NOT NULL,
PhuongThucThanhToan NVARCHAR(50) NOT NULL,
CachVanChuyen NVARCHAR(50) NOT NULL,
MaGioHang INT NOT NULL,
MaNguoiDung INT NOT NULL,
FOREIGN KEY (MaGioHang) REFERENCES GioHang(MaGioHang),
FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
);
GO
CREATE TABLE Quyen (
MaQuyen INT PRIMARY KEY IDENTITY(1,1),
TenQuyen NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE PhanQuyen (

MaNguoiDung INT NOT NULL,
MaQuyen INT NOT NULL,
FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung),
FOREIGN KEY (MaQuyen) REFERENCES Quyen(MaQuyen)
);
GO
ALTER TABLE PhanQuyen ADD MaPhanQuyen INT PRIMARY KEY IDENTITY(1,1)


INSERT INTO  Taikhoan(TenTaiKhoan,MatKhau,Email) VALUES(N'TrieuVy','123','trieuvy@gmail.com')

